/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasPrincipales;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import vistas.InternalFramesGestionAdministraTivo.AsignacionEstudiante;
import vistas.InternalFramesGestionAdministraTivo.GestionEstudiante;
import vistas.InternalFramesGestionAdministraTivo.GestionDocente;
import vistas.InternalFramesGestionAdministraTivo.GestionCursos;
import vistas.InternalFramesGestionAdministraTivo.GestionAdminLab;
import vistas.InternalFramesGestionAdministraTivo.GestionarHorarios;

/**
 *
 * @author Juan Manuel
 */
public class GestionAdministrativo extends javax.swing.JFrame {

    /**
     * Creates new form GestionAdministraTivo2
     */
    public GestionAdministrativo() {
        initComponents();
        this.setLocationRelativeTo(this);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menuAdminLab = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        menuDocente = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        menuEstudiante = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        menuCurso = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        jMenuBar2.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar2.setForeground(new java.awt.Color(71, 100, 104));
        jMenuBar2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setText("Atras");
        jMenu4.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        menuAdminLab.setBackground(new java.awt.Color(0, 0, 0));
        menuAdminLab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuAdminLab.setForeground(new java.awt.Color(0, 0, 0));
        menuAdminLab.setText("Administrador de Laboratorio");
        menuAdminLab.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N

        jMenu10.setText("Gestionar Administrador Laboratorio");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });
        menuAdminLab.add(jMenu10);

        jMenuBar2.add(menuAdminLab);

        menuDocente.setBackground(new java.awt.Color(0, 0, 0));
        menuDocente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuDocente.setForeground(new java.awt.Color(0, 0, 0));
        menuDocente.setText("Docente");
        menuDocente.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N

        jMenu11.setText("Gestionar Docente");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        menuDocente.add(jMenu11);

        jMenuBar2.add(menuDocente);

        menuEstudiante.setBackground(new java.awt.Color(0, 0, 0));
        menuEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        menuEstudiante.setText("Estudiante");
        menuEstudiante.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N

        jMenu12.setText("Gestionar Estudiante");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        menuEstudiante.add(jMenu12);

        jMenuBar2.add(menuEstudiante);

        menuCurso.setBackground(new java.awt.Color(0, 0, 0));
        menuCurso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuCurso.setForeground(new java.awt.Color(0, 0, 0));
        menuCurso.setText("Curso");
        menuCurso.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N

        jMenu13.setText("Crear Curso");
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        menuCurso.add(jMenu13);

        jMenu14.setText("Asignar Horarios");
        jMenu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu14MouseClicked(evt);
            }
        });
        menuCurso.add(jMenu14);

        jMenu5.setText("Asignar Estudiantes");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        menuCurso.add(jMenu5);

        jMenuBar2.add(menuCurso);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed

    }//GEN-LAST:event_jMenu10ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
         escritorio.removeAll();
        GestionAdminLab lab = new GestionAdminLab();
        escritorio.add(lab);
        lab.setVisible(true);
        lab.setResizable(false);
        try {
            lab.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GestionAdministrativo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
         escritorio.removeAll();
        GestionDocente doc = new GestionDocente();        
        escritorio.add(doc);
        doc.setVisible(true);
        try {
            doc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GestionAdministrativo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        escritorio.removeAll();
        GestionEstudiante estudi = new GestionEstudiante();
        escritorio.add(estudi);
        estudi.setVisible(true);
        try {
            estudi.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GestionAdministrativo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
       escritorio.removeAll();
       GestionCursos curo = new GestionCursos();
       escritorio.add(curo);
       curo.setVisible(true);
        try {
            curo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GestionAdministrativo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu13MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
      Login log = new Login();
      log.setVisible(true);
      log.setLocationRelativeTo(this);
      this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu14MouseClicked
        escritorio.removeAll();
        GestionarHorarios ges = new GestionarHorarios();
        escritorio.add(ges);
        ges.setVisible(true);
        try {
            ges.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GestionAdministrativo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu14MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
       escritorio.removeAll();
        AsignacionEstudiante estu = new AsignacionEstudiante();
       escritorio.add(estu);
        estu.setVisible(true);
        try {
            estu.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GestionAdministrativo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAdministrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAdminLab;
    private javax.swing.JMenu menuCurso;
    private javax.swing.JMenu menuDocente;
    private javax.swing.JMenu menuEstudiante;
    // End of variables declaration//GEN-END:variables
}
