/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.AdminLab;

import controladores.AdminLab.controladorMantenimiento;
import javax.swing.table.DefaultTableModel;
import modelado.AdminLaboratorio;
import modelado.Mantenimiento;

/**
 *
 * @author Juan Manuel
 */
public class MantenimientosActivos extends javax.swing.JFrame {
AdminLaboratorio admin;
controladorMantenimiento control;
    public MantenimientosActivos(AdminLaboratorio admin) {
        initComponents();
        this.control = new controladorMantenimiento();
        this.setLocationRelativeTo(this);
        this.admin = admin;
        actualizarTablaMantenimiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimiento = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("MANTENIMIENTOS ACTIVOS");

        tblMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Laboratorio", "Fecha Inicial", "Fecha Final", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMantenimiento);
        if (tblMantenimiento.getColumnModel().getColumnCount() > 0) {
            tblMantenimiento.getColumnModel().getColumn(0).setResizable(false);
            tblMantenimiento.getColumnModel().getColumn(1).setResizable(false);
            tblMantenimiento.getColumnModel().getColumn(2).setResizable(false);
            tblMantenimiento.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AdminLabInicio ini = new AdminLabInicio(admin);
       ini.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void actualizarTablaMantenimiento() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblMantenimiento.getModel();
        modeloTabla.setRowCount(0);
        Mantenimiento man;
        for (int i = 0; i < control.getListaMantenimiento().size(); i++) {
                man =  control.getListaMantenimiento().get(i);
                String[] rowData = {
                    man.getLaboratorio().getNumeroLab(),
                    man.getFechaMantenimientoInicial().toString(),
                    man.getFechaMantenimientoFinal().toString(),
                    man.getDescripcion()
                    
                };
                modeloTabla.addRow(rowData);
            

        }
        tblMantenimiento.setModel(modeloTabla);
        tblMantenimiento.revalidate();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMantenimiento;
    // End of variables declaration//GEN-END:variables
}
