/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.Estudiante;

import controladores.Estudiante.controladorNotas;
import controladores.administrativo.ControladorCurso;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelado.Curso;
import modelado.Detalle;
import modelado.Estudiante;

/**
 *
 * @author Juan Manuel
 */
public class NotasEstudiante extends javax.swing.JFrame {

    controladorNotas contronEstudiante;
    ControladorCurso control;
    Estudiante estudiante;

    public NotasEstudiante(Estudiante estudiante) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.control = new ControladorCurso();
        this.estudiante = estudiante;
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("NOTAS CURSOS");

        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Curso", "Nota 1", "Nota 2", "Nota 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbCursos);

        jLabel2.setText("CURSOS:");

        cbCursos.setBackground(new java.awt.Color(71, 100, 104));
        cbCursos.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbCursos.setForeground(new java.awt.Color(255, 255, 255));
        cbCursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCursosItemStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
          private void llenarCombo() {
        cbCursos.removeAll();
        for (int i = 0; i < control.getListaCursos().size(); i++) {
            for (int j = 0; j < control.getListaCursos().get(i).getListaEstudiantes().size(); j++) {
                if (control.getListaCursos().get(i).getListaEstudiantes().get(j).getId().equals(estudiante.getId())) {
                    cbCursos.addItem(control.getListaCursos().get(i));
                }
            }
        }
    }
    private void cbCursosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCursosItemStateChanged
        Curso curso = (Curso) cbCursos.getSelectedItem();
        this.contronEstudiante = new controladorNotas(curso, estudiante);
        actualizarTabla(curso, estudiante);
    }//GEN-LAST:event_cbCursosItemStateChanged
    private void actualizarTabla(Curso curso, Estudiante estudianteD) {
        try {
            String notaTotal = contronEstudiante.calcularPorcentajeTotal(curso, estudiante);
            DefaultTableModel modelo = new DefaultTableModel(new String[]{"Curso", "Nota1", "Nota2", "Nota3", "Total",},
                    curso.getListaNotas().size());
            tbCursos.setModel(modelo);
            TableModel modeloDatos = tbCursos.getModel();

            modeloDatos.setValueAt(curso.getMateria().toString(), 0, 0);
            for (int i = 0; i < curso.getListaNotas().size(); i++) {
                for (int j = 0; j < curso.getListaNotas().get(i).getListaDetalles().size(); j++) {
                    if (curso.getListaNotas().get(i).getListaDetalles().get(j).getEstudinate().getId().equals(estudianteD.getId())) {
                        Detalle detalle1 = curso.getListaNotas().get(i).getListaDetalles().get(j);
                        if (detalle1.isCalificado()) {
                            modeloDatos.setValueAt(String.valueOf(detalle1.getValor()), 0, i + 1);
                            modeloDatos.setValueAt(notaTotal, 0, 4);
                        } else {
                            modeloDatos.setValueAt("No calificado", 0, i + 1);
                        }
                    }
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {

        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InicioEstudiante es = new InicioEstudiante(estudiante);
        es.setVisible(true);
        es.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Curso> cbCursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCursos;
    // End of variables declaration//GEN-END:variables
}
