/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.InternalFramesGestionAdministraTivo;

import com.toedter.calendar.JTextFieldDateEditor;
import controladores.ControladorAdminLab;
import controladores.ControladorEstudiante;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelado.Enums.Programa;
import modelado.Estudiante;
import modelado.Persona;

/**
 *
 * @author Juan Manuel
 */
public class GestionEstudiante extends javax.swing.JInternalFrame {

      ControladorEstudiante control;
    public GestionEstudiante() {
        initComponents();
          this.control = new ControladorEstudiante();
        actualizarTablaEstudiante();
           JTextFieldDateEditor editor4 = (JTextFieldDateEditor) dateEstudiante.getDateEditor();
        editor4.setEditable(false);
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estudiante = new javax.swing.JPanel();
        dateEstudiante = new com.toedter.calendar.JDateChooser();
        txtIdentificacionEstudiante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnInsertarEstudiante = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnBuscarEstudiante = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnBorrarEstudiante = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnActualizarEstudiante = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtUsuarioEstudiante = new javax.swing.JTextField();
        txtContraEstudiante = new javax.swing.JPasswordField();
        txtNombreEstudiante = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEstudiante = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        cbProgramas = new javax.swing.JComboBox();

        jLabel11.setText("NOMBRE  DE  USUARIO:");

        btnInsertarEstudiante.setText("INSERTAR");
        btnInsertarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarEstudianteActionPerformed(evt);
            }
        });

        jLabel12.setText("CONTRASEÑA TEMPORAL:");

        btnBuscarEstudiante.setText("BUSCAR");
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });

        jLabel13.setText("NOMBRE :");

        btnBorrarEstudiante.setText("BORRAR");
        btnBorrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEstudianteActionPerformed(evt);
            }
        });

        jLabel14.setText("IDENTIFICACION");

        btnActualizarEstudiante.setText("ACTUALIZAR");
        btnActualizarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEstudianteActionPerformed(evt);
            }
        });

        jLabel15.setText("Fecha De Nacimiento");

        tblEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "identificacion", "Nombre de Usuario", "Contraseña", "Programa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEstudiante);

        jLabel16.setText("PROGRAMA");

        javax.swing.GroupLayout EstudianteLayout = new javax.swing.GroupLayout(Estudiante);
        Estudiante.setLayout(EstudianteLayout);
        EstudianteLayout.setHorizontalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudianteLayout.createSequentialGroup()
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstudianteLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EstudianteLayout.createSequentialGroup()
                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstudianteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dateEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))
                            .addGroup(EstudianteLayout.createSequentialGroup()
                                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EstudianteLayout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnInsertarEstudiante)
                                            .addComponent(btnBuscarEstudiante))
                                        .addGap(25, 25, 25)
                                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnActualizarEstudiante)
                                            .addGroup(EstudianteLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(btnBorrarEstudiante))))
                                    .addGroup(EstudianteLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsuarioEstudiante)
                                            .addComponent(txtContraEstudiante)
                                            .addComponent(txtNombreEstudiante)
                                            .addComponent(txtIdentificacionEstudiante)
                                            .addComponent(cbProgramas, 0, 199, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EstudianteLayout.setVerticalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudianteLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstudianteLayout.createSequentialGroup()
                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtUsuarioEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtContraEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtIdentificacionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarEstudiante)
                    .addComponent(btnBorrarEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarEstudiante)
                    .addComponent(btnBuscarEstudiante))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void llenarCombo(){
      cbProgramas.removeAllItems();
        for (Programa value : Programa.values()) {
            cbProgramas.addItem(value);
        }
    }
    
    private void btnInsertarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarEstudianteActionPerformed
        String nombreUser = txtUsuarioEstudiante.getText();
        String contrasena = String.valueOf(txtContraEstudiante.getPassword());
        String nombre = txtNombreEstudiante.getText();
        String id = txtIdentificacionEstudiante.getText();
        Date fecha = dateEstudiante.getDate();
        LocalDate fechaNacimiento = fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        Programa programa = (Programa) cbProgramas.getSelectedItem();
        Estudiante estu = new Estudiante(nombre, id, fechaNacimiento, nombreUser, contrasena, programa,"Estudiante");
        control.agregarEstudiante(estu);
        actualizarTablaEstudiante();
    }//GEN-LAST:event_btnInsertarEstudianteActionPerformed
       private void actualizarTablaEstudiante() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblEstudiante.getModel();
        modeloTabla.setRowCount(0);
        Estudiante estudiante;
        for (int i = 0; i < control.getListaPersonas().size(); i++) {
            if (control.getListaPersonas().get(i) instanceof Estudiante) {
                estudiante = (Estudiante) control.getListaPersonas().get(i);
                String[] rowData = {
                    estudiante.getNombre(),
                    estudiante.getId(),
                    estudiante.getNommbreUsuario(),
                    estudiante.getContrasena(),
                    estudiante.getPrograma().toString()
                };
                modeloTabla.addRow(rowData);
            }

        }
        tblEstudiante.setModel(modeloTabla);
        tblEstudiante.revalidate();
    }
    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        try {
            String id = txtIdentificacionEstudiante.getText();
            Persona persona = control.buscarPersonal(id);
            if (persona instanceof Estudiante) {
                Date fecha = java.sql.Date.valueOf(persona.getFechaNacimiento());
                dateEstudiante.setDate(fecha);
                txtNombreEstudiante.setText(persona.getNombre());
                txtContraEstudiante.setText(persona.getContrasena());
                txtUsuarioEstudiante.setText(persona.getNommbreUsuario());
                cbProgramas.setSelectedItem(((Estudiante) persona).getPrograma());
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se encuentra el Estudiante");
        }
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void btnBorrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEstudianteActionPerformed
        if (txtIdentificacionEstudiante.equals("")) {
            JOptionPane.showMessageDialog(null, "LLene el campo del id para poder borrar el usuario");
        }
        String id = txtIdentificacionEstudiante.getText();
        control.eliminarEstudiante(id);
        actualizarTablaEstudiante();
    }//GEN-LAST:event_btnBorrarEstudianteActionPerformed

    private void btnActualizarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEstudianteActionPerformed
        String nombreUser = txtUsuarioEstudiante.getText();
        String contrasena = String.valueOf(txtContraEstudiante.getPassword());
        String nombre = txtNombreEstudiante.getText();
        String id = txtIdentificacionEstudiante.getText();
        Date fecha = dateEstudiante.getDate();
        LocalDate fechaNacimiento = fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        Programa program = (Programa) cbProgramas.getSelectedItem();
        Estudiante estudi = new Estudiante(nombre, id, fechaNacimiento, nombreUser, contrasena, program,"Estudiante");
        control.ActualizarEstudiante(estudi);
        actualizarTablaEstudiante();
    }//GEN-LAST:event_btnActualizarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Estudiante;
    private javax.swing.JButton btnActualizarEstudiante;
    private javax.swing.JButton btnBorrarEstudiante;
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnInsertarEstudiante;
    private javax.swing.JComboBox cbProgramas;
    private com.toedter.calendar.JDateChooser dateEstudiante;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblEstudiante;
    private javax.swing.JPasswordField txtContraEstudiante;
    private javax.swing.JTextField txtIdentificacionEstudiante;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtUsuarioEstudiante;
    // End of variables declaration//GEN-END:variables
}
