/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.InternalFramesGestionAdministraTivo;

import controladores.administrativo.ControladorAdminLab;
import controladores.administrativo.ControladorCurso;
import excepciones.NoSeEncuentraCursoException;
import excepciones.cursoYaExisteException;
import excepciones.yaEstaCreadoCursoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelado.Curso;
import modelado.Docente;
import modelado.Enums.Dias;
import modelado.Enums.Materia;
import modelado.Enums.Programa;
import modelado.Persona;
import util.IList;

/**
 *
 * @author Juan Manuel
 */
public class GestionCursos extends javax.swing.JInternalFrame {

    ControladorCurso control;

    public GestionCursos() {
        initComponents();
        this.control = new ControladorCurso();
        llenarCombo();
        llenarComboPrograma();
        actualizarTablaAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cursos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cbDocente = new javax.swing.JComboBox<>();
        btnBorrarCurso = new javax.swing.JButton();
        btnInsertarCurso = new javax.swing.JButton();
        btnBuscarCurso = new javax.swing.JButton();
        btnActualizarCurso = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        cbJornada = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnDehacer = new javax.swing.JButton();
        cbProgramas = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        btnRehacer = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cursos.setBackground(new java.awt.Color(0, 39, 44));
        Cursos.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DOCENTE ASIGNADO:");
        Cursos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        cbDocente.setBackground(new java.awt.Color(71, 100, 104));
        cbDocente.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbDocente.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.add(cbDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 93, 510, -1));

        btnBorrarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnBorrarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnBorrarCurso.setText("BORRAR");
        btnBorrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnBorrarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 110, -1));

        btnInsertarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnInsertarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnInsertarCurso.setText("INSERTAR");
        btnInsertarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnInsertarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        btnBuscarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnBuscarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnBuscarCurso.setText("BUSCAR");
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnBuscarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 340, 100, -1));

        btnActualizarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnActualizarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnActualizarCurso.setText("ACTUALIZAR");
        btnActualizarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnActualizarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CODIGO DE CURSO:");
        Cursos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));

        txtCodigoCurso.setBackground(new java.awt.Color(71, 100, 104));
        txtCodigoCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        txtCodigoCurso.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoCurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoCursoFocusLost(evt);
            }
        });
        txtCodigoCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoCursoKeyTyped(evt);
            }
        });
        Cursos.add(txtCodigoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 270, -1));

        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materias", "Docente", "Periodo", "Jornada", "Programa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbCursos);

        Cursos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 710, 126));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("JORNADA :");
        Cursos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 108, -1));

        cbJornada.setBackground(new java.awt.Color(71, 100, 104));
        cbJornada.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbJornada.setForeground(new java.awt.Color(255, 255, 255));
        cbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche" }));
        Cursos.add(cbJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("REGISTRO DE CURSOS");
        Cursos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 260, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("MATERIA:");
        Cursos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 76, -1));

        cbMaterias.setBackground(new java.awt.Color(71, 100, 104));
        cbMaterias.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbMaterias.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.add(cbMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 59, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Curso.png"))); // NOI18N
        Cursos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 160, 160));

        btnDehacer.setBackground(new java.awt.Color(71, 100, 104));
        btnDehacer.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnDehacer.setForeground(new java.awt.Color(0, 0, 0));
        btnDehacer.setText("DESHACER");
        btnDehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDehacerActionPerformed(evt);
            }
        });
        Cursos.add(btnDehacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        cbProgramas.setBackground(new java.awt.Color(71, 100, 104));
        cbProgramas.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbProgramas.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.add(cbProgramas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 270, -1));

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PROGRAMA:");
        Cursos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, -1));

        btnRehacer.setBackground(new java.awt.Color(71, 100, 104));
        btnRehacer.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnRehacer.setForeground(new java.awt.Color(0, 0, 0));
        btnRehacer.setText("REHACER");
        btnRehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRehacerActionPerformed(evt);
            }
        });
        Cursos.add(btnRehacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        getContentPane().add(Cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCursoActionPerformed
        String id = txtCodigoCurso.getText();

        try {
            control.eliminarCurso(id);
            actualizarTablaAdmin();
        } catch (cursoYaExisteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_btnBorrarCursoActionPerformed

    private void llenarComboPrograma() {
        cbProgramas.removeAllItems();
        for (Programa value : Programa.values()) {
            cbProgramas.addItem(value);
        }
    }

    private void llenarCombo() {
        cbDocente.removeAllItems();
        IList<Persona> lista = control.getListaPersonas();
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i) instanceof Docente) {
                cbDocente.addItem((Docente) lista.get(i));
            }
        }
        cbMaterias.removeAllItems();
        Materia[] materias = Materia.values();
        for (int i = 1; i < materias.length - 1; i++) {
            cbMaterias.addItem(materias[i]);
        }

    }

    private boolean camposVacios() {
        if (txtCodigoCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }


    private void btnInsertarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCursoActionPerformed
        if (camposVacios()) {
            return;
        }
        Docente docente = (Docente) cbDocente.getSelectedItem();
        String codigoCurso = txtCodigoCurso.getText();
        String periodo = control.validarPeriodoAnio();
        System.out.println(periodo);
        String jornada = cbJornada.getSelectedItem().toString();
        Materia materia = (Materia) cbMaterias.getSelectedItem();
        Programa programa = (Programa) cbProgramas.getSelectedItem();
        Curso curso = new Curso(programa, materia, docente, periodo, codigoCurso, jornada);
        try {
            control.agregarCurso(curso);
            actualizarTablaAdmin();

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No hay docentes Registrados");
            return;
        } catch (cursoYaExisteException | yaEstaCreadoCursoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }


    }//GEN-LAST:event_btnInsertarCursoActionPerformed
    private void actualizarTablaAdmin() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tbCursos.getModel();
        modeloTabla.setRowCount(0);
        String periodoActual = control.validarPeriodoAnio();
        Curso curso;
        for (int i = 0; i < control.getListaCursos().size(); i++) {
            if (control.getListaCursos().get(i).getPeriodo().equals(periodoActual)) {
                curso = control.getListaCursos().get(i);
                String[] rowData = {
                    curso.getMateria().toString(),
                    curso.getDocente().getNombre(),
                    curso.getPeriodo(),
                    curso.getJornada(),
                    curso.getPrograma().toString()
                };
                modeloTabla.addRow(rowData);
            }
        }
        tbCursos.setModel(modeloTabla);
        tbCursos.revalidate();
    }
    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        try {
            if (camposVacios()) {
                return;
            }
            String id = txtCodigoCurso.getText();
            Curso curso = control.buscarCurso(id);
            cbDocente.setSelectedItem(curso.getDocente());
            cbJornada.setSelectedItem(curso.getJornada());
            cbMaterias.setSelectedItem(curso.getMateria());
            cbProgramas.setSelectedItem(curso.getPrograma());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se encuentra el Curso");
        }
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnActualizarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCursoActionPerformed
        if (camposVacios()) {
            return;
        }
        Docente docente = (Docente) cbDocente.getSelectedItem();
        String codigoCurso = txtCodigoCurso.getText();
        String periodo = control.validarPeriodoAnio();
        String jornada = cbJornada.getSelectedItem().toString();
        Materia materia = (Materia) cbMaterias.getSelectedItem();
        Programa programa = (Programa) cbProgramas.getSelectedItem();
        Curso curso = new Curso(programa, materia, docente, periodo, codigoCurso, jornada);
        try {
            control.ActualizarCurso(curso);
            actualizarTablaAdmin();
        } catch (NoSeEncuentraCursoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnActualizarCursoActionPerformed

    private void txtCodigoCursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoCursoFocusLost
        if (txtCodigoCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Este campo es Obligatorio", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCodigoCursoFocusLost

    private void txtCodigoCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoCursoKeyTyped
        char num = evt.getKeyChar();
        if (num < '0' || num > '9')
            evt.consume();
    }//GEN-LAST:event_txtCodigoCursoKeyTyped

    private void btnDehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDehacerActionPerformed
        try {
            try {
                control.dehacer();
                 actualizarTablaAdmin();
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "No hay acciones para hacer");
            }

        } catch (cursoYaExisteException | yaEstaCreadoCursoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

       
    }//GEN-LAST:event_btnDehacerActionPerformed

    private void btnRehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRehacerActionPerformed
        try {
             try {
                control.rehacer();
                actualizarTablaAdmin();
            } catch (NullPointerException e) {
                 JOptionPane.showMessageDialog(null, "No hay acciones para hacer");
            }
        } catch (cursoYaExisteException | yaEstaCreadoCursoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

       
    
    }//GEN-LAST:event_btnRehacerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cursos;
    private javax.swing.JButton btnActualizarCurso;
    private javax.swing.JButton btnBorrarCurso;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnDehacer;
    private javax.swing.JButton btnInsertarCurso;
    private javax.swing.JButton btnRehacer;
    private javax.swing.JComboBox<Docente> cbDocente;
    private javax.swing.JComboBox<String> cbJornada;
    private javax.swing.JComboBox cbMaterias;
    private javax.swing.JComboBox cbProgramas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbCursos;
    private javax.swing.JTextField txtCodigoCurso;
    // End of variables declaration//GEN-END:variables
}
