/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.InternalFramesGestionAdministraTivo;

import com.toedter.calendar.JTextFieldDateEditor;
import controladores.ControladorAdminLab;
import controladores.ControladorDocente;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelado.Docente;
import modelado.Persona;

/**
 *
 * @author Juan Manuel
 */
public class GestionDocente extends javax.swing.JInternalFrame {

    ControladorDocente control;
    public GestionDocente() {
        initComponents();
           this.control = new ControladorDocente();
           actualizarTablaDocente();
             JTextFieldDateEditor editor3 = (JTextFieldDateEditor) dateDocente.getDateEditor();
        editor3.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Docente = new javax.swing.JPanel();
        dateDocente = new com.toedter.calendar.JDateChooser();
        txtIdentificacionDocente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnInsertarDocente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarDocente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnBorrarDocente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnActualizarDocente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtUsuarioDocente = new javax.swing.JTextField();
        txtContraDocente = new javax.swing.JPasswordField();
        txtNombreDocente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDocente = new javax.swing.JTable();

        txtIdentificacionDocente.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NOMBRE  DE  USUARIO:");

        btnInsertarDocente.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnInsertarDocente.setForeground(new java.awt.Color(0, 0, 0));
        btnInsertarDocente.setText("INSERTAR");
        btnInsertarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarDocenteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CONTRASEÑA TEMPORAL:");

        btnBuscarDocente.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnBuscarDocente.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarDocente.setText("BUSCAR");
        btnBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDocenteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NOMBRE :");

        btnBorrarDocente.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnBorrarDocente.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrarDocente.setText("BORRAR");
        btnBorrarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarDocenteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("IDENTIFICACION");

        btnActualizarDocente.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnActualizarDocente.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarDocente.setText("ACTUALIZAR");
        btnActualizarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDocenteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha De Nacimiento");

        txtUsuarioDocente.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        txtContraDocente.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        txtNombreDocente.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        tblDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "identificacion", "Nombre de Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDocente);

        javax.swing.GroupLayout DocenteLayout = new javax.swing.GroupLayout(Docente);
        Docente.setLayout(DocenteLayout);
        DocenteLayout.setHorizontalGroup(
            DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocenteLayout.createSequentialGroup()
                .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DocenteLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DocenteLayout.createSequentialGroup()
                                .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuarioDocente)
                                    .addComponent(txtContraDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txtNombreDocente)
                                    .addComponent(txtIdentificacionDocente)))))
                    .addGroup(DocenteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnInsertarDocente)
                                .addComponent(btnBuscarDocente)))
                        .addGap(25, 25, 25)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarDocente)
                            .addGroup(DocenteLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnBorrarDocente)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        DocenteLayout.setVerticalGroup(
            DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocenteLayout.createSequentialGroup()
                .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DocenteLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUsuarioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtContraDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtIdentificacionDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(dateDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertarDocente)
                            .addComponent(btnBorrarDocente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizarDocente)
                            .addComponent(btnBuscarDocente)))
                    .addGroup(DocenteLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarDocenteActionPerformed
        String nombreUser = txtUsuarioDocente.getText();
        String contrasena = String.valueOf(txtContraDocente.getPassword());
        String nombre = txtNombreDocente.getText();
        String id = txtIdentificacionDocente.getText();
        // para agarrar el dia por medio de DATE
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE");
        Date fecha = dateDocente.getDate();
        System.out.println(sdf.format(dateDocente.getDate()));
        LocalDate fechaNacimiento = fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        Docente docente = new Docente(nombre, id, fechaNacimiento, nombreUser, contrasena,"Docente");
        control.agregarDocente(docente);
        actualizarTablaDocente();
    }//GEN-LAST:event_btnInsertarDocenteActionPerformed
      private void actualizarTablaDocente() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblDocente.getModel();
        modeloTabla.setRowCount(0);
        Docente docente;
        for (int i = 0; i < control.getListaPersonas().size(); i++) {
            if (control.getListaPersonas().get(i) instanceof Docente) {
                docente = (Docente) control.getListaPersonas().get(i);
                String[] rowData = {
                    docente.getNombre(),
                    docente.getId(),
                    docente.getNommbreUsuario(),
                    docente.getContrasena()
                };
                modeloTabla.addRow(rowData);
            }

        }
        tblDocente.setModel(modeloTabla);
        tblDocente.revalidate();
    }
    private void btnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocenteActionPerformed

        try {
            String id = txtIdentificacionDocente.getText();
            Persona persona = control.buscarPersonal(id);
            Date fecha = java.sql.Date.valueOf(persona.getFechaNacimiento());
            dateDocente.setDate(fecha);
            txtNombreDocente.setText(persona.getNombre());
            txtContraDocente.setText(persona.getContrasena());
            txtUsuarioDocente.setText(persona.getNommbreUsuario());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se encuentra el Docente");
        }
    }//GEN-LAST:event_btnBuscarDocenteActionPerformed

    private void btnBorrarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarDocenteActionPerformed
        if (txtIdentificacionDocente.equals("")) {
            JOptionPane.showMessageDialog(null, "LLene el campo del id para poder borrar el usuario");
        }
        String id = txtIdentificacionDocente.getText();
        control.eliminarDocente(id);
        actualizarTablaDocente();
    }//GEN-LAST:event_btnBorrarDocenteActionPerformed

    private void btnActualizarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDocenteActionPerformed
        String nombreUser = txtUsuarioDocente.getText();
        String contrasena = String.valueOf(txtContraDocente.getPassword());
        String nombre = txtNombreDocente.getText();
        String id = txtIdentificacionDocente.getText();
        Date fecha = dateDocente.getDate();
        LocalDate fechaNacimiento = fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        Docente docente = new Docente(nombre, id, fechaNacimiento, nombreUser, contrasena,"Docente");
        control.ActualizarDocente(docente);
        actualizarTablaDocente();
    }//GEN-LAST:event_btnActualizarDocenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Docente;
    private javax.swing.JButton btnActualizarDocente;
    private javax.swing.JButton btnBorrarDocente;
    private javax.swing.JButton btnBuscarDocente;
    private javax.swing.JButton btnInsertarDocente;
    private com.toedter.calendar.JDateChooser dateDocente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDocente;
    private javax.swing.JPasswordField txtContraDocente;
    private javax.swing.JTextField txtIdentificacionDocente;
    private javax.swing.JTextField txtNombreDocente;
    private javax.swing.JTextField txtUsuarioDocente;
    // End of variables declaration//GEN-END:variables
}
