/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.InternalFramesGestionAdministraTivo;

import controladores.administrativo.ControladorAdminLab;
import controladores.administrativo.ControladorCurso;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelado.Curso;
import modelado.Docente;
import modelado.Enums.Dias;
import modelado.Enums.Materia;
import modelado.Persona;
import util.IList;

/**
 *
 * @author Juan Manuel
 */
public class GestionCursos extends javax.swing.JInternalFrame {

    ControladorCurso control;

    public GestionCursos() {
        initComponents();
        this.control = new ControladorCurso();
        llenarCombo();
        actualizarTablaAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cursos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cbDocente = new javax.swing.JComboBox<>();
        btnBorrarCurso = new javax.swing.JButton();
        btnInsertarCurso = new javax.swing.JButton();
        btnBuscarCurso = new javax.swing.JButton();
        btnActualizarCurso = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cbJornada = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox();
        cbPeriodo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cursos.setBackground(new java.awt.Color(0, 39, 44));
        Cursos.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DOCENTE ASIGNADO:");
        Cursos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        cbDocente.setBackground(new java.awt.Color(71, 100, 104));
        cbDocente.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbDocente.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.add(cbDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 93, 270, -1));

        btnBorrarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnBorrarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnBorrarCurso.setText("BORRAR");
        btnBorrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnBorrarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 307, -1, -1));

        btnInsertarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnInsertarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnInsertarCurso.setText("INSERTAR");
        btnInsertarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnInsertarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 307, -1, -1));

        btnBuscarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnBuscarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnBuscarCurso.setText("BUSCAR");
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnBuscarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 358, -1, -1));

        btnActualizarCurso.setBackground(new java.awt.Color(71, 100, 104));
        btnActualizarCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnActualizarCurso.setText("ACTUALIZAR");
        btnActualizarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCursoActionPerformed(evt);
            }
        });
        Cursos.add(btnActualizarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 358, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CODIGO DE CURSO:");
        Cursos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));

        txtCodigoCurso.setBackground(new java.awt.Color(71, 100, 104));
        txtCodigoCurso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        txtCodigoCurso.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.add(txtCodigoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 270, -1));

        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Materias", "Docente", "Periodo", "Jornada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbCursos);

        Cursos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 710, 126));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PERIODO DEL AÑO:");
        Cursos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 150, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("JORNADA :");
        Cursos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 108, -1));

        cbJornada.setBackground(new java.awt.Color(71, 100, 104));
        cbJornada.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbJornada.setForeground(new java.awt.Color(255, 255, 255));
        cbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Noche" }));
        Cursos.add(cbJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("REGISTRO DE CURSOS");
        Cursos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 260, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("MATERIA:");
        Cursos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 76, -1));

        cbMaterias.setBackground(new java.awt.Color(71, 100, 104));
        cbMaterias.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbMaterias.setForeground(new java.awt.Color(255, 255, 255));
        Cursos.add(cbMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 59, 270, -1));

        cbPeriodo.setBackground(new java.awt.Color(71, 100, 104));
        cbPeriodo.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cbPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024-1", "2024-2" }));
        Cursos.add(cbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Curso.png"))); // NOI18N
        Cursos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 160, 160));

        getContentPane().add(Cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCursoActionPerformed
        String id = txtCodigoCurso.getText();
        try {
            control.eliminarCurso(id);
            actualizarTablaAdmin();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se encuentra el Curso");
        }
    }//GEN-LAST:event_btnBorrarCursoActionPerformed

    private void llenarCombo() {
        cbDocente.removeAllItems();
        IList<Persona> lista = control.getListaPersonas();
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i) instanceof Docente) {
                cbDocente.addItem((Docente) lista.get(i));
            }
        }
        cbMaterias.removeAllItems();
        Materia[] materias = Materia.values();
        for (int i = 1; i < materias.length - 1; i++) {
            cbMaterias.addItem(materias[i]);
        }

    }

    private void btnInsertarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCursoActionPerformed

        Docente docente = (Docente) cbDocente.getSelectedItem();
        String codigoCurso = txtCodigoCurso.getText();
        String periodo = cbPeriodo.getSelectedItem().toString();
        System.out.println(periodo);
        String jornada = cbJornada.getSelectedItem().toString();
        Materia materia = (Materia) cbMaterias.getSelectedItem();
        Curso curso = new Curso(materia, docente, periodo, codigoCurso, jornada);
        try {
            control.agregarCurso(curso);
            actualizarTablaAdmin();

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No hay docentes Registrados");
        }


    }//GEN-LAST:event_btnInsertarCursoActionPerformed
    private void actualizarTablaAdmin() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tbCursos.getModel();
        modeloTabla.setRowCount(0);
        Curso curso;
        for (int i = 0; i < control.getListaCursos().size(); i++) {
            curso = control.getListaCursos().get(i);
            String[] rowData = {
                curso.getMateria().toString(),
                curso.getDocente().getNombre(),
                curso.getPeriodo(),
                curso.getJornada(),};
            modeloTabla.addRow(rowData);
        }
        tbCursos.setModel(modeloTabla);
        tbCursos.revalidate();
    }
    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        try {
            String id = txtCodigoCurso.getText();
            Curso curso = control.buscarCurso(id);
            cbDocente.setSelectedItem(curso.getDocente());
            cbPeriodo.setSelectedItem(curso.getPeriodo());
            cbJornada.setSelectedItem(curso.getJornada());
            cbMaterias.setSelectedItem(curso.getMateria());

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se encuentra el Curso");
        }
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnActualizarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCursoActionPerformed

        Docente docente = (Docente) cbDocente.getSelectedItem();
        String codigoCurso = txtCodigoCurso.getText();
        String periodo = cbPeriodo.getSelectedItem().toString();
        System.out.println(periodo);
        String jornada = cbJornada.getSelectedItem().toString();
        Materia materia = (Materia) cbMaterias.getSelectedItem();
        Curso curso = new Curso(materia, docente, periodo, codigoCurso, jornada);
        control.ActualizarCurso(curso);
        actualizarTablaAdmin();
    }//GEN-LAST:event_btnActualizarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cursos;
    private javax.swing.JButton btnActualizarCurso;
    private javax.swing.JButton btnBorrarCurso;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnInsertarCurso;
    private javax.swing.JComboBox<Docente> cbDocente;
    private javax.swing.JComboBox<String> cbJornada;
    private javax.swing.JComboBox cbMaterias;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbCursos;
    private javax.swing.JTextField txtCodigoCurso;
    // End of variables declaration//GEN-END:variables
}
