/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.administrativo.ControladorIniciarSesion;
import excepciones.UsuarioNoEncontradoException;
import javax.swing.JOptionPane;
import modelado.AdminLaboratorio;
import modelado.Administrativo;
import modelado.Docente;
import modelado.Estudiante;
import modelado.Persona;

/**
 *
 * @author Juan Manuel
 */
public class Login extends javax.swing.JFrame {

    ControladorIniciarSesion control;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = new ControladorIniciarSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtContrasena = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        botonExit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(640, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContrasena.setBackground(new java.awt.Color(71, 100, 104));
        txtContrasena.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txtContrasena.setBorder(null);
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 121, -1));

        txtUsuario.setBackground(new java.awt.Color(71, 100, 104));
        txtUsuario.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(22, 45, 50));
        txtUsuario.setBorder(null);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 130, -1));

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("LOGIN");
        btnEntrar.setBorder(null);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 280, 40));

        botonExit.setBackground(new java.awt.Color(0, 44, 49));
        botonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExitMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 44, 49));
        jLabel1.setForeground(new java.awt.Color(0, 44, 49));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/XOficial.png"))); // NOI18N

        javax.swing.GroupLayout botonExitLayout = new javax.swing.GroupLayout(botonExit);
        botonExit.setLayout(botonExitLayout);
        botonExitLayout.setHorizontalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        botonExitLayout.setVerticalGroup(
            botonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonExitLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 30, 30));

        loginPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginoficila.png"))); // NOI18N
        loginPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginPhotoMouseClicked(evt);
            }
        });
        jPanel1.add(loginPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
         JTextFieldDateEditor editor = (JTextFieldDateEditor) dateAdminLab.getDateEditor();
        editor.setEditable(false);
        JTextFieldDateEditor editor2 = (JTextFieldDateEditor) dateDiaCurso.getDateEditor();
        editor2.setEditable(false);
        JTextFieldDateEditor editor3 = (JTextFieldDateEditor) dateDocente.getDateEditor();
        editor3.setEditable(false);
        JTextFieldDateEditor editor4 = (JTextFieldDateEditor) dateEstudiante.getDateEditor();
        editor4.setEditable(false);
    
    */
    
    
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String usuario = txtUsuario.getText();
        String contra = String.valueOf(txtContrasena.getPassword());
        try {
            Persona persona = control.login(usuario, contra);
            System.out.println(persona.getRol());
            switch (persona.getRol()) {
                case "adminGeneral" -> {
                    RegistroAdministrativo administra = new RegistroAdministrativo();
                    administra.setVisible(true);
                    administra.setLocationRelativeTo(this);
                    this.dispose();
                }
                case "administrativo" -> {
                    GestionAdministrativo ven = new GestionAdministrativo();
                    ven.setVisible(true);
                    ven.setLocationRelativeTo(this);
                    this.dispose();
                }
                case "Estudiante" -> {
                }
                case "Docente" -> {
                }
                case "AdminLab" -> {
                }
                default -> {
                }
            }

        } catch (UsuarioNoEncontradoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btnEntrarActionPerformed

    private void loginPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPhotoMouseClicked

    }//GEN-LAST:event_loginPhotoMouseClicked

    private void botonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseClicked
         System.exit(0);
    }//GEN-LAST:event_botonExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonExit;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginPhoto;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
